spring.application.name=smartpc
#Configuration for database connection
spring.datasource.url=jdbc:mysql://localhost:3306/smartpc
spring.datasource.username=root
spring.datasource.password=senai

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server configuration
server.port=8088

